!> \brief Fortran 包装器 — 将 POINT_TO_MESH 数据扁平化后传递给 C++ mass_routines

MODULE MASS

USE PRECISION_PARAMETERS
USE TYPES, ONLY: SPECIES_MIXTURE_TYPE, SPECIES_TYPE, WALL_TYPE, CELL_TYPE, &
                 BOUNDARY_COORD_TYPE, BOUNDARY_PROP1_TYPE, EXTERNAL_WALL_TYPE

USE PRECISION_PARAMETERS
USE TYPES, ONLY: SPECIES_MIXTURE_TYPE, SPECIES_TYPE, WALL_TYPE, CELL_TYPE, &
                 BOUNDARY_COORD_TYPE, BOUNDARY_PROP1_TYPE, EXTERNAL_WALL_TYPE
USE MESH_POINTERS
USE GLOBAL_CONSTANTS, ONLY: PREDICTOR, FIRST_PASS, SOLID_PHASE_ONLY, N_TRACKED_SPECIES, &
    N_TOTAL_SCALARS, N_ZONE, N_PASSIVE_SCALARS, ZETA_INDEX, &
    CC_IBM, STORE_SPECIES_FLUX, I_FLUX_LIMITER, FLUX_LIMITER_MW_CORRECTION, &
    PERIODIC_TEST, ICYC, RHOMIN, RHOMAX, &
    GRAVITATIONAL_SETTLING, THERMOPHORETIC_SETTLING, &
    GVEC, R0, N_SURFACE_DENSITY_SPECIES, D_Z, T_USED
USE ISO_C_BINDING
USE PHYSICAL_FUNCTIONS, ONLY: GET_SPECIFIC_GAS_CONSTANT, GET_MOLECULAR_WEIGHT
USE MATH_FUNCTIONS, ONLY: GET_SCALAR_FACE_VALUE
USE COMP_FUNCTIONS, ONLY: CURRENT_TIME

IMPLICIT NONE (TYPE,EXTERNAL)

PRIVATE
PUBLIC MASS_FINITE_DIFFERENCES,DENSITY


TYPE, BIND(C) :: MASS_MP_C

  TYPE(C_PTR) :: U, V, W
  TYPE(C_PTR) :: US, VS, WS
  TYPE(C_PTR) :: RHO, RHOS
  TYPE(C_PTR) :: TMP, RSUM, MU, Q, D_SOURCE

  TYPE(C_PTR) :: ZZ, ZZS
  TYPE(C_PTR) :: DEL_RHO_D_DEL_Z
  TYPE(C_PTR) :: FX, FY, FZ
  TYPE(C_PTR) :: M_DOT_PPP
  TYPE(C_PTR) :: ADV_FX, ADV_FY, ADV_FZ

  TYPE(C_PTR) :: R, RC, RRN
  TYPE(C_PTR) :: DX, RDX, RDXN
  TYPE(C_PTR) :: DY, RDY, DYN, RDYN
  TYPE(C_PTR) :: DZ, RDZ, DZN, RDZN
  TYPE(C_PTR) :: XC, ZC

  TYPE(C_PTR) :: WORK1, WORK2, WORK3, WORK4, WORK5
  TYPE(C_PTR) :: SWORK4

  TYPE(C_PTR) :: PBAR, PBAR_S
  TYPE(C_PTR) :: PRESSURE_ZONE
  TYPE(C_PTR) :: D_PBAR_DT, D_PBAR_DT_S

  TYPE(C_PTR) :: CELL_INDEX
  TYPE(C_PTR) :: CELL_SOLID
  TYPE(C_PTR) :: CELL_WALL_INDEX
  TYPE(C_PTR) :: CELL_EXTERIOR
  TYPE(C_PTR) :: UVW_SAVE

  TYPE(C_PTR) :: WALL_BC_TYPE
  TYPE(C_PTR) :: WALL_B1_INDEX
  TYPE(C_PTR) :: BC_IIG, BC_JJG, BC_KKG, BC_IOR
  TYPE(C_PTR) :: BC_II, BC_JJ, BC_KK
  TYPE(C_PTR) :: BP1_RHO_F
  TYPE(C_PTR) :: BP1_ZZ_F
  TYPE(C_PTR) :: EWC_BOUNDARY_TYPE_PREVIOUS

  INTEGER(C_INT) :: IBAR, JBAR, KBAR
  INTEGER(C_INT) :: IBP1, JBP1, KBP1
  INTEGER(C_INT) :: N_EXTERNAL_WALL_CELLS, N_INTERNAL_WALL_CELLS
  INTEGER(C_INT) :: N_ZONE
  INTEGER(C_INT) :: N_TOTAL_SCALARS, N_TRACKED_SPECIES
  INTEGER(C_INT) :: N_PASSIVE_SCALARS, ZETA_INDEX

  INTEGER(C_INT) :: PREDICTOR_FLAG
  INTEGER(C_INT) :: FIRST_PASS_FLAG
  INTEGER(C_INT) :: CC_IBM_FLAG
  INTEGER(C_INT) :: STORE_SPECIES_FLUX_FLAG
  INTEGER(C_INT) :: I_FLUX_LIMITER
  INTEGER(C_INT) :: FLUX_LIMITER_MW_CORRECTION_FLAG
  INTEGER(C_INT) :: PERIODIC_TEST_VAL
  INTEGER(C_INT) :: ICYC_VAL
  INTEGER(C_INT) :: SOLID_PHASE_ONLY_FLAG
  INTEGER(C_INT) :: GRAVITATIONAL_SETTLING_FLAG
  INTEGER(C_INT) :: THERMOPHORETIC_SETTLING_FLAG
  REAL(C_DOUBLE) :: RHOMIN_VAL, RHOMAX_VAL
  ! --- SPECIES_MIXTURE ---
  TYPE(C_PTR) :: SM_MW
  TYPE(C_PTR) :: SM_DEPOSITING
  ! --- SPECIES ---
  TYPE(C_PTR) :: SP_DENSITY_SOLID
END TYPE MASS_MP_C


REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_MW_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_DEPOSITING_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SP_DENSITY_SOLID_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: CELL_WALL_INDEX_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: CELL_EXTERIOR_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: CELL_SOLID_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: WALL_BC_TYPE_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: WALL_B1_INDEX_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: BC_IIG_TMP(:), BC_JJG_TMP(:), BC_KKG_TMP(:), BC_IOR_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: BC_II_TMP(:), BC_JJ_TMP(:), BC_KK_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_RHO_F_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_ZZ_F_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: EWC_BOUNDARY_TYPE_PREVIOUS_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: UVW_SAVE_TMP(:)

INTEGER, SAVE :: PREV_NW = -1, PREV_NTS = -1, PREV_NSPEC = -1, PREV_NC = -1
LOGICAL, SAVE :: ARRAYS_ALLOCATED = .FALSE.

INTERFACE
  SUBROUTINE mass_c_finite_differences(mp) BIND(C)
    IMPORT :: MASS_MP_C
    TYPE(MASS_MP_C), INTENT(INOUT) :: mp
  END SUBROUTINE
  SUBROUTINE mass_c_density(T, DT, mp) BIND(C)
    USE ISO_C_BINDING, ONLY: C_DOUBLE
    IMPORT :: MASS_MP_C
    REAL(C_DOUBLE), INTENT(IN), VALUE :: T, DT
    TYPE(MASS_MP_C), INTENT(INOUT) :: mp
  END SUBROUTINE
END INTERFACE

CONTAINS

SUBROUTINE ENSURE_WALL(NW)
  INTEGER, INTENT(IN) :: NW
  IF (ARRAYS_ALLOCATED .AND. NW == PREV_NW) RETURN
  IF (ALLOCATED(WALL_BC_TYPE_TMP)) DEALLOCATE(WALL_BC_TYPE_TMP, WALL_B1_INDEX_TMP,&
    BC_IIG_TMP, BC_JJG_TMP, BC_KKG_TMP, BC_IOR_TMP, BC_II_TMP, BC_JJ_TMP, BC_KK_TMP,&
    BP1_RHO_F_TMP, BP1_ZZ_F_TMP,&
    EWC_BOUNDARY_TYPE_PREVIOUS_TMP, UVW_SAVE_TMP)
  ALLOCATE(WALL_BC_TYPE_TMP(NW), WALL_B1_INDEX_TMP(NW),&
    BC_IIG_TMP(NW), BC_JJG_TMP(NW), BC_KKG_TMP(NW), BC_IOR_TMP(NW),&
    BC_II_TMP(NW), BC_JJ_TMP(NW), BC_KK_TMP(NW),&
    BP1_RHO_F_TMP(NW), BP1_ZZ_F_TMP(NW * N_TRACKED_SPECIES),&
    EWC_BOUNDARY_TYPE_PREVIOUS_TMP(NW), UVW_SAVE_TMP(NW))
  PREV_NW = NW
END SUBROUTINE ENSURE_WALL

SUBROUTINE ENSURE_SPECIES(NTS)
  INTEGER, INTENT(IN) :: NTS
  IF (ARRAYS_ALLOCATED .AND. NTS == PREV_NTS) RETURN
  IF (ALLOCATED(SM_MW_TMP)) DEALLOCATE(SM_MW_TMP, SM_DEPOSITING_TMP)
  ALLOCATE(SM_MW_TMP(NTS), SM_DEPOSITING_TMP(NTS))
  PREV_NTS = NTS
END SUBROUTINE ENSURE_SPECIES

SUBROUTINE ENSURE_CELL(NC)
  INTEGER, INTENT(IN) :: NC
  IF (ARRAYS_ALLOCATED .AND. NC == PREV_NC) RETURN
  IF (ALLOCATED(CELL_SOLID_TMP)) DEALLOCATE(CELL_SOLID_TMP, CELL_WALL_INDEX_TMP, CELL_EXTERIOR_TMP)
  ALLOCATE(CELL_SOLID_TMP(NC), CELL_WALL_INDEX_TMP(NC*7), CELL_EXTERIOR_TMP(NC))
  PREV_NC = NC
END SUBROUTINE ENSURE_CELL

SUBROUTINE PACK_MP_C(mp)
  TYPE(MASS_MP_C), INTENT(INOUT) :: mp
  INTEGER :: I,J,K,IW,II,JJ,KK,IC,NTS,NW,NC,NSPEC
  TYPE(WALL_TYPE), POINTER :: WC
  TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
  TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1
  TYPE(EXTERNAL_WALL_TYPE), POINTER :: EWC

  NTS = N_TRACKED_SPECIES
  NW  = N_EXTERNAL_WALL_CELLS + N_INTERNAL_WALL_CELLS
  NC  = (IBAR+1)*(JBAR+1)*(KBAR+1)


  mp%U  = C_LOC(U(LBOUND(U,1),LBOUND(U,2),LBOUND(U,3)))
  mp%V  = C_LOC(V(LBOUND(V,1),LBOUND(V,2),LBOUND(V,3)))
  mp%W  = C_LOC(W(LBOUND(W,1),LBOUND(W,2),LBOUND(W,3)))
  mp%US = C_LOC(US(LBOUND(US,1),LBOUND(US,2),LBOUND(US,3)))
  mp%VS = C_LOC(VS(LBOUND(VS,1),LBOUND(VS,2),LBOUND(VS,3)))
  mp%WS = C_LOC(WS(LBOUND(WS,1),LBOUND(WS,2),LBOUND(WS,3)))
  mp%RHO  = C_LOC(RHO(LBOUND(RHO,1),LBOUND(RHO,2),LBOUND(RHO,3)))
  mp%RHOS = C_LOC(RHOS(LBOUND(RHOS,1),LBOUND(RHOS,2),LBOUND(RHOS,3)))
  mp%TMP  = C_LOC(TMP(LBOUND(TMP,1),LBOUND(TMP,2),LBOUND(TMP,3)))
  mp%RSUM = C_LOC(RSUM(LBOUND(RSUM,1),LBOUND(RSUM,2),LBOUND(RSUM,3)))
  mp%MU   = C_LOC(MU(LBOUND(MU,1),LBOUND(MU,2),LBOUND(MU,3)))
  mp%Q    = C_LOC(Q(LBOUND(Q,1),LBOUND(Q,2),LBOUND(Q,3)))
  mp%D_SOURCE = C_LOC(D_SOURCE(LBOUND(D_SOURCE,1),LBOUND(D_SOURCE,2),LBOUND(D_SOURCE,3)))


  mp%ZZ  = C_LOC(ZZ(LBOUND(ZZ,1),LBOUND(ZZ,2),LBOUND(ZZ,3),LBOUND(ZZ,4)))
  mp%ZZS = C_LOC(ZZS(LBOUND(ZZS,1),LBOUND(ZZS,2),LBOUND(ZZS,3),LBOUND(ZZS,4)))
  mp%DEL_RHO_D_DEL_Z = C_LOC(DEL_RHO_D_DEL_Z(LBOUND(DEL_RHO_D_DEL_Z,1),LBOUND(DEL_RHO_D_DEL_Z,2),&
    LBOUND(DEL_RHO_D_DEL_Z,3),LBOUND(DEL_RHO_D_DEL_Z,4)))
  mp%FX = C_LOC(FX(LBOUND(FX,1),LBOUND(FX,2),LBOUND(FX,3),LBOUND(FX,4)))
  mp%FY = C_LOC(FY(LBOUND(FY,1),LBOUND(FY,2),LBOUND(FY,3),LBOUND(FY,4)))
  mp%FZ = C_LOC(FZ(LBOUND(FZ,1),LBOUND(FZ,2),LBOUND(FZ,3),LBOUND(FZ,4)))
  mp%M_DOT_PPP = C_LOC(M_DOT_PPP(LBOUND(M_DOT_PPP,1),LBOUND(M_DOT_PPP,2),&
    LBOUND(M_DOT_PPP,3),LBOUND(M_DOT_PPP,4)))
  mp%ADV_FX = C_LOC(ADV_FX(LBOUND(ADV_FX,1),LBOUND(ADV_FX,2),LBOUND(ADV_FX,3),LBOUND(ADV_FX,4)))
  mp%ADV_FY = C_LOC(ADV_FY(LBOUND(ADV_FY,1),LBOUND(ADV_FY,2),LBOUND(ADV_FY,3),LBOUND(ADV_FY,4)))
  mp%ADV_FZ = C_LOC(ADV_FZ(LBOUND(ADV_FZ,1),LBOUND(ADV_FZ,2),LBOUND(ADV_FZ,3),LBOUND(ADV_FZ,4)))


  mp%R    = C_LOC(R(LBOUND(R,1)))
  mp%RC   = C_LOC(RC(LBOUND(RC,1)))
  mp%RRN  = C_LOC(RRN(LBOUND(RRN,1)))
  mp%DX   = C_LOC(DX(LBOUND(DX,1)))
  mp%RDX  = C_LOC(RDX(LBOUND(RDX,1)))
  mp%RDXN = C_LOC(RDXN(LBOUND(RDXN,1)))
  mp%DY   = C_LOC(DY(LBOUND(DY,1)))
  mp%RDY  = C_LOC(RDY(LBOUND(RDY,1)))
  mp%DYN  = C_LOC(DYN(LBOUND(DYN,1)))
  mp%RDYN = C_LOC(RDYN(LBOUND(RDYN,1)))
  mp%DZ   = C_LOC(DZ(LBOUND(DZ,1)))
  mp%RDZ  = C_LOC(RDZ(LBOUND(RDZ,1)))
  mp%DZN  = C_LOC(DZN(LBOUND(DZN,1)))
  mp%RDZN = C_LOC(RDZN(LBOUND(RDZN,1)))
  mp%XC   = C_LOC(XC(LBOUND(XC,1)))
  mp%ZC   = C_LOC(ZC(LBOUND(ZC,1)))


  mp%WORK1 = C_LOC(WORK1(LBOUND(WORK1,1),LBOUND(WORK1,2),LBOUND(WORK1,3)))
  mp%WORK2 = C_LOC(WORK2(LBOUND(WORK2,1),LBOUND(WORK2,2),LBOUND(WORK2,3)))
  mp%WORK3 = C_LOC(WORK3(LBOUND(WORK3,1),LBOUND(WORK3,2),LBOUND(WORK3,3)))
  mp%WORK4 = C_LOC(WORK4(LBOUND(WORK4,1),LBOUND(WORK4,2),LBOUND(WORK4,3)))
  mp%WORK5 = C_LOC(WORK5(LBOUND(WORK5,1),LBOUND(WORK5,2),LBOUND(WORK5,3)))
  mp%SWORK4= C_LOC(SWORK4(LBOUND(SWORK4,1),LBOUND(SWORK4,2),LBOUND(SWORK4,3),LBOUND(SWORK4,4)))

  mp%PBAR = C_LOC(PBAR(LBOUND(PBAR,1),LBOUND(PBAR,2)))
  mp%PBAR_S = C_LOC(PBAR_S(LBOUND(PBAR_S,1),LBOUND(PBAR_S,2)))
  mp%PRESSURE_ZONE = C_LOC(PRESSURE_ZONE(LBOUND(PRESSURE_ZONE,1),LBOUND(PRESSURE_ZONE,2),&
    LBOUND(PRESSURE_ZONE,3)))
  mp%D_PBAR_DT  = C_LOC(D_PBAR_DT(1))
  mp%D_PBAR_DT_S = C_LOC(D_PBAR_DT_S(1))


  mp%CELL_INDEX = C_LOC(CELL_INDEX(LBOUND(CELL_INDEX,1),LBOUND(CELL_INDEX,2),LBOUND(CELL_INDEX,3)))

  CALL ENSURE_CELL(NC)
  CELL_SOLID_TMP(:) = 0.0_EB
  CELL_EXTERIOR_TMP(:) = 0.0_EB
  CELL_WALL_INDEX_TMP(:) = 0
  DO K = 0, KBAR
    DO J = 0, JBAR
      DO I = 0, IBAR
        IC = CELL_INDEX(I, J, K)
        IF (IC > 0) THEN
          CELL_SOLID_TMP(IC) = MERGE(1.0_EB, 0.0_EB, CELL(IC)%SOLID)
          CELL_EXTERIOR_TMP(IC) = MERGE(1.0_EB, 0.0_EB, CELL(IC)%EXTERIOR)
          CELL_WALL_INDEX_TMP( (IC-1)*7+1 : IC*7 ) = (/ CELL(IC)%WALL_INDEX(-3), CELL(IC)%WALL_INDEX(-2), &
            CELL(IC)%WALL_INDEX(-1), 0, CELL(IC)%WALL_INDEX(1), CELL(IC)%WALL_INDEX(2), CELL(IC)%WALL_INDEX(3) /)
        ENDIF
      ENDDO
    ENDDO
  ENDDO
  mp%CELL_SOLID = C_LOC(CELL_SOLID_TMP(1))
  mp%CELL_WALL_INDEX = C_LOC(CELL_WALL_INDEX_TMP(1))
  mp%CELL_EXTERIOR = C_LOC(CELL_EXTERIOR_TMP(1))


  CALL ENSURE_WALL(NW)

  ! UVW_SAVE
  DO IW = 1, N_EXTERNAL_WALL_CELLS
    UVW_SAVE_TMP(IW) = UVW_SAVE(IW)
  ENDDO
  mp%UVW_SAVE = C_LOC(UVW_SAVE_TMP(1))
  DO IW = 1, NW
    WC => WALL(IW)
    BC => BOUNDARY_COORD(WC%BC_INDEX)
    B1 => BOUNDARY_PROP1(WC%B1_INDEX)
    WALL_BC_TYPE_TMP(IW) = WC%BOUNDARY_TYPE
    WALL_B1_INDEX_TMP(IW) = WC%B1_INDEX
    BC_IIG_TMP(IW) = BC%IIG
    BC_JJG_TMP(IW) = BC%JJG
    BC_KKG_TMP(IW) = BC%KKG
    BC_IOR_TMP(IW) = BC%IOR
    BC_II_TMP(IW) = BC%II
    BC_JJ_TMP(IW) = BC%JJ
    BC_KK_TMP(IW) = BC%KK
    BP1_RHO_F_TMP(IW) = B1%RHO_F
    BP1_ZZ_F_TMP((IW-1)*NTS+1 : IW*NTS) = B1%ZZ_F(1:NTS)
  ENDDO
  mp%WALL_BC_TYPE = C_LOC(WALL_BC_TYPE_TMP(1))
  mp%WALL_B1_INDEX = C_LOC(WALL_B1_INDEX_TMP(1))
  mp%BC_IIG = C_LOC(BC_IIG_TMP(1))
  mp%BC_JJG = C_LOC(BC_JJG_TMP(1))
  mp%BC_KKG = C_LOC(BC_KKG_TMP(1))
  mp%BC_IOR = C_LOC(BC_IOR_TMP(1))
  mp%BC_II = C_LOC(BC_II_TMP(1))
  mp%BC_JJ = C_LOC(BC_JJ_TMP(1))
  mp%BC_KK = C_LOC(BC_KK_TMP(1))
  mp%BP1_RHO_F = C_LOC(BP1_RHO_F_TMP(1))
  mp%BP1_ZZ_F = C_LOC(BP1_ZZ_F_TMP(1))

  ! EXTERNAL_WALL
  DO IW = 1, N_EXTERNAL_WALL_CELLS
    EWC => EXTERNAL_WALL(IW)
    EWC_BOUNDARY_TYPE_PREVIOUS_TMP(IW) = EWC%BOUNDARY_TYPE_PREVIOUS
  ENDDO
  mp%EWC_BOUNDARY_TYPE_PREVIOUS = C_LOC(EWC_BOUNDARY_TYPE_PREVIOUS_TMP(1))


  CALL ENSURE_SPECIES(NTS)
  DO I = 1, NTS
    SM_MW_TMP(I) = SPECIES_MIXTURE(I)%MW
    SM_DEPOSITING_TMP(I) = MERGE(1.0_EB, 0.0_EB, SPECIES_MIXTURE(I)%DEPOSITING)
  ENDDO
  mp%SM_MW = C_LOC(SM_MW_TMP(1))
  mp%SM_DEPOSITING = C_LOC(SM_DEPOSITING_TMP(1))


  mp%IBAR = IBAR; mp%JBAR = JBAR; mp%KBAR = KBAR
  mp%IBP1 = IBAR+1; mp%JBP1 = JBAR+1; mp%KBP1 = KBAR+1
  mp%N_EXTERNAL_WALL_CELLS = N_EXTERNAL_WALL_CELLS
  mp%N_INTERNAL_WALL_CELLS = N_INTERNAL_WALL_CELLS
  mp%N_ZONE = N_ZONE
  mp%N_TOTAL_SCALARS = N_TOTAL_SCALARS
  mp%N_TRACKED_SPECIES = N_TRACKED_SPECIES
  mp%N_PASSIVE_SCALARS = N_PASSIVE_SCALARS
  mp%ZETA_INDEX = ZETA_INDEX
  mp%PREDICTOR_FLAG = MERGE(1, 0, PREDICTOR)
  mp%FIRST_PASS_FLAG = MERGE(1, 0, FIRST_PASS)
  mp%CC_IBM_FLAG = MERGE(1, 0, CC_IBM)
  mp%STORE_SPECIES_FLUX_FLAG = MERGE(1, 0, STORE_SPECIES_FLUX)
  mp%I_FLUX_LIMITER = I_FLUX_LIMITER
  mp%FLUX_LIMITER_MW_CORRECTION_FLAG = MERGE(1, 0, FLUX_LIMITER_MW_CORRECTION)
  mp%PERIODIC_TEST_VAL = PERIODIC_TEST
  mp%ICYC_VAL = ICYC
  mp%SOLID_PHASE_ONLY_FLAG = MERGE(1, 0, SOLID_PHASE_ONLY)
  mp%GRAVITATIONAL_SETTLING_FLAG = MERGE(1, 0, GRAVITATIONAL_SETTLING)
  mp%THERMOPHORETIC_SETTLING_FLAG = MERGE(1, 0, THERMOPHORETIC_SETTLING)
  mp%RHOMIN_VAL = REAL(RHOMIN, C_DOUBLE)
  mp%RHOMAX_VAL = REAL(RHOMAX, C_DOUBLE)
  mp%SP_DENSITY_SOLID = C_NULL_PTR
END SUBROUTINE PACK_MP_C


SUBROUTINE MASS_FINITE_DIFFERENCES(NM)
  INTEGER, INTENT(IN) :: NM
  TYPE(MASS_MP_C) :: mp
  REAL(EB) :: TNOW

  IF (SOLID_PHASE_ONLY) RETURN
  TNOW = CURRENT_TIME()
  CALL POINT_TO_MESH(NM)
  IF (PREDICTOR) DT_RESTRICT_COUNT = 0

  CALL PACK_MP_C(mp)
  CALL mass_c_finite_differences(mp)

  T_USED(3) = T_USED(3) + CURRENT_TIME() - TNOW
END SUBROUTINE MASS_FINITE_DIFFERENCES


SUBROUTINE DENSITY(T, DT, NM)
  USE SOOT_ROUTINES, ONLY: SETTLING_VELOCITY
  USE CC_SCALARS, ONLY: SET_EXIMADVFLX_3D, ROTATED_CUBE_RHS_ZZ
  USE MANUFACTURED_SOLUTIONS, ONLY: VD2D_MMS_Z_SRC, UF_MMS, WF_MMS
  INTEGER, INTENT(IN) :: NM
  REAL(EB), INTENT(IN) :: T, DT
  TYPE(MASS_MP_C) :: mp
  REAL(EB) :: TNOW

  IF (SOLID_PHASE_ONLY) RETURN
  SELECT CASE (PERIODIC_TEST)
    CASE DEFAULT
      IF (ICYC <= 1) RETURN
    CASE (5, 8)
      RETURN
    CASE (4, 7, 11, 21, 22)
  END SELECT
  TNOW = CURRENT_TIME()
  CALL POINT_TO_MESH(NM)

  ! FIRST_PASS 时调用 SETTLING_VELOCITY (PREDICTOR 步)
  IF (PREDICTOR .AND. FIRST_PASS) THEN
    IF (ANY(SPECIES_MIXTURE%DEPOSITING) .AND. &
        (GRAVITATIONAL_SETTLING .OR. THERMOPHORETIC_SETTLING)) CALL SETTLING_VELOCITY(NM)
  ENDIF

  ! CORRECTOR 步的 SETTLING_VELOCITY
  IF (.NOT. PREDICTOR) THEN
    IF (ANY(SPECIES_MIXTURE%DEPOSITING) .AND. &
        (GRAVITATIONAL_SETTLING .OR. THERMOPHORETIC_SETTLING)) CALL SETTLING_VELOCITY(NM)
  ENDIF

  CALL PACK_MP_C(mp)
  CALL mass_c_density(REAL(T, C_DOUBLE), REAL(DT, C_DOUBLE), mp)

  ! 后处理: CC_IBM
  IF (CC_IBM) THEN
    IF (PREDICTOR) THEN
      CALL SET_EXIMADVFLX_3D(NM, WORK1, WORK2, WORK3)
    ELSE
      CALL SET_EXIMADVFLX_3D(NM, WORK1, WORK2, WORK3)
    ENDIF
  ENDIF

  T_USED(3) = T_USED(3) + CURRENT_TIME() - TNOW
END SUBROUTINE DENSITY


SUBROUTINE fds_get_scalar_face_value(uu_ptr, scalar_ptr, face_ptr, &
    ilo, ihi, jlo, jhi, klo, khi, dir, i_flux_limiter, &
    ni, nj, nk) BIND(C, NAME="fds_get_scalar_face_value")
  USE ISO_C_BINDING, ONLY: C_DOUBLE, C_INT, C_PTR
  USE MATH_FUNCTIONS, ONLY: GET_SCALAR_FACE_VALUE
  IMPLICIT NONE
  TYPE(C_PTR), INTENT(IN), VALUE :: uu_ptr, scalar_ptr, face_ptr
  INTEGER(C_INT), INTENT(IN), VALUE :: ilo, ihi, jlo, jhi, klo, khi, dir, &
                                        i_flux_limiter, ni, nj, nk
  REAL(EB), POINTER, DIMENSION(:,:,:) :: uu, scalar, face
  CALL C_F_POINTER(uu_ptr, uu, [ni, nj, nk])
  CALL C_F_POINTER(scalar_ptr, scalar, [ni, nj, nk])
  CALL C_F_POINTER(face_ptr, face, [ni, nj, nk])
  CALL GET_SCALAR_FACE_VALUE(uu, scalar, face, ilo, ihi, jlo, jhi, &
                              klo, khi, dir, i_flux_limiter)
END SUBROUTINE fds_get_scalar_face_value

END MODULE MASS
