!> \brief Fortran 包装器 — 将 POINT_TO_MESH 数据扁平化后传递给 C++ soot_routines


MODULE SOOT_ROUTINES

USE PRECISION_PARAMETERS
USE TYPES, ONLY: SPECIES_MIXTURE_TYPE, SPECIES_TYPE, WALL_TYPE, CFACE_TYPE, &
                 BOUNDARY_COORD_TYPE, BOUNDARY_PROP1_TYPE, BOUNDARY_PROP2_TYPE, &
                 LAGRANGIAN_PARTICLE_TYPE, CELL_TYPE, SPECIES_MIXTURE, SPECIES
USE MESH_POINTERS
USE GLOBAL_CONSTANTS, ONLY: N_PARTICLE_BINS,MIN_PARTICLE_DIAMETER,MAX_PARTICLE_DIAMETER,K_BOLTZMANN, &
                            N_TRACKED_SPECIES,GRAV,AGGLOMERATION_SMIX_INDEX,AGGLOMERATION_SPEC_INDEX, &
                            N_AGGLOMERATION_SPECIES,GVEC,NULL_BOUNDARY,OPEN_BOUNDARY,INTERPOLATED_BOUNDARY, &
                            GRAVITATIONAL_SETTLING,THERMOPHORETIC_SETTLING,PREDICTOR, &
                            SOOT_INDEX,O2_INDEX,R0,MW_O2,ZZ_MIN_GLOBAL,NU_SOOT_OX,D_Z, &
                            N_SURFACE_DENSITY_SPECIES, I_MAX_TEMP
USE ISO_C_BINDING
USE PHYSICAL_FUNCTIONS, ONLY: GET_VISCOSITY,GET_CONDUCTIVITY,GET_MASS_FRACTION, &
    GET_MOLECULAR_WEIGHT,GET_SPECIFIC_HEAT,GET_SPECIFIC_GAS_CONSTANT,GET_AVERAGE_SPECIFIC_HEAT
IMPLICIT NONE (TYPE,EXTERNAL)

PUBLIC CALC_AGGLOMERATION, INITIALIZE_AGGLOMERATION,SETTLING_VELOCITY,PARTICLE_RADIUS, SOOT_SURFACE_OXIDATION, DROPLET_SCRUBBING

PRIVATE

TYPE, BIND(C) :: SOOT_MP_C

  TYPE(C_PTR) :: U, V, W
  TYPE(C_PTR) :: RHO, RHOS
  TYPE(C_PTR) :: TMP, MU
  TYPE(C_PTR) :: Q, D_SOURCE, RSUM

  TYPE(C_PTR) :: ZZ, ZZS
  TYPE(C_PTR) :: DEL_RHO_D_DEL_Z
  TYPE(C_PTR) :: FX, FY, FZ
  TYPE(C_PTR) :: M_DOT_PPP

  TYPE(C_PTR) :: R, RC, RRN
  TYPE(C_PTR) :: DX, RDX, RDXN
  TYPE(C_PTR) :: DY, RDY, DYN, RDYN
  TYPE(C_PTR) :: DZ, RDZ, DZN, RDZN
  TYPE(C_PTR) :: PBAR
  TYPE(C_PTR) :: PRESSURE_ZONE
  TYPE(C_PTR) :: CELL_INDEX
  INTEGER(C_INT) :: IBAR, JBAR, KBAR
  INTEGER(C_INT) :: N_EXTERNAL_WALL_CELLS, N_INTERNAL_WALL_CELLS
  INTEGER(C_INT) :: INTERNAL_CFACE_CELLS_LB, N_INTERNAL_CFACE_CELLS
  INTEGER(C_INT) :: N_SPECIES

  TYPE(C_PTR) :: WALL_BC_TYPE
  TYPE(C_PTR) :: WALL_BC_INDEX
  TYPE(C_PTR) :: WALL_B1_INDEX
  TYPE(C_PTR) :: BC_IIG, BC_JJG, BC_KKG, BC_IOR
  TYPE(C_PTR) :: BP1_AREA, BP1_TMP_F
  TYPE(C_PTR) :: BP1_RHO_G, BP1_TMP_G
  TYPE(C_PTR) :: BP1_AWM_AEROSOL
  TYPE(C_PTR) :: BP1_ZZ_G

  TYPE(C_PTR) :: CFACE_BC_TYPE
  TYPE(C_PTR) :: CFACE_B1_INDEX
  TYPE(C_PTR) :: CFACE_BC_INDEX
  TYPE(C_PTR) :: CFACE_RSUM_G

  TYPE(C_PTR) :: LP_U, LP_V, LP_W
  TYPE(C_PTR) :: LP_RADIUS, LP_RVC, LP_PWT
  TYPE(C_PTR) :: LP_BC_INDEX, LP_B1_INDEX

  REAL(C_DOUBLE) :: LP_U_VAL, LP_V_VAL, LP_W_VAL
  REAL(C_DOUBLE) :: LP_RADIUS_VAL, LP_RVC_VAL, LP_PWT_VAL
  INTEGER(C_INT) :: LP_BC_INDEX_VAL, LP_B1_INDEX_VAL
  INTEGER(C_INT) :: LP_IIG_VAL, LP_JJG_VAL, LP_KKG_VAL
  REAL(C_DOUBLE) :: LP_BP1_AREA_VAL, LP_BP1_TMP_F_VAL
  REAL(C_DOUBLE) :: LP_BP1_RHO_G_VAL, LP_BP1_TMP_G_VAL

  TYPE(C_PTR) :: CELL_SOLID

  TYPE(C_PTR) :: WORK7, WORK8, WORK9

  INTEGER(C_INT) :: PREDICTOR_FLAG
  INTEGER(C_INT) :: N_TRACKED_SPECIES
  REAL(C_DOUBLE) :: GVEC_X, GVEC_Y, GVEC_Z
  INTEGER(C_INT) :: NULL_BOUNDARY_VAL, OPEN_BOUNDARY_VAL, INTERPOLATED_BOUNDARY_VAL
  INTEGER(C_INT) :: N_AGGLOMERATION_SPECIES
  INTEGER(C_INT) :: SOOT_INDEX, O2_INDEX
  INTEGER(C_INT) :: N_SURFACE_DENSITY_SPECIES
  REAL(C_DOUBLE) :: R0_VAL, MW_O2_VAL, ZZ_MIN_GLOBAL_VAL
  TYPE(C_PTR) :: NU_SOOT_OX
  INTEGER(C_INT) :: I_MAX_TEMP_VAL, N_TOTAL_SCALARS_VAL

  TYPE(C_PTR) :: SM_DEPOSITING
  TYPE(C_PTR) :: SM_MEAN_DIAMETER, SM_DENSITY_SOLID
  TYPE(C_PTR) :: SM_THERMOPHORETIC_DIAMETER, SM_CONDUCTIVITY_SOLID
  TYPE(C_PTR) :: SM_H_F, SM_RCON, SM_MW
  TYPE(C_PTR) :: SM_AWM_INDEX, SM_AGGLOMERATION_INDEX
  TYPE(C_PTR) :: D_Z_PTR

  TYPE(C_PTR) :: SP_DENSITY_SOLID, SP_CONDUCTIVITY_SOLID
  TYPE(C_PTR) :: SP_AWM_INDEX, SP_AGGLOMERATING

  TYPE(C_PTR) :: N_PARTICLE_BINS
  TYPE(C_PTR) :: AGGLOMERATION_SPEC_INDEX, AGGLOMERATION_SMIX_INDEX
  TYPE(C_PTR) :: MIN_PARTICLE_DIAMETER, MAX_PARTICLE_DIAMETER
END TYPE SOOT_MP_C


REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_DEPOSITING_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_MEAN_DIAMETER_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_DENSITY_SOLID_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_THERMOPHORETIC_DIAMETER_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_CONDUCTIVITY_SOLID_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_H_F_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_RCON_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SM_MW_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: SM_AWM_INDEX_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: SM_AGGLOMERATION_INDEX_TMP(:)

REAL(EB), ALLOCATABLE, TARGET, SAVE :: SP_DENSITY_SOLID_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SP_CONDUCTIVITY_SOLID_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: SP_AWM_INDEX_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: SP_AGGLOMERATING_TMP(:)

INTEGER, ALLOCATABLE, TARGET, SAVE :: WALL_BC_TYPE_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: WALL_BC_INDEX_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: WALL_B1_INDEX_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: BC_IIG_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: BC_JJG_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: BC_KKG_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: BC_IOR_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_AREA_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_TMP_F_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_RHO_G_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_TMP_G_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_AWM_AEROSOL_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_ZZ_G_TMP(:)

INTEGER, ALLOCATABLE, TARGET, SAVE :: CFACE_BC_TYPE_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: CFACE_B1_INDEX_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: CFACE_BC_INDEX_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: CFACE_RSUM_G_TMP(:)

INTEGER, ALLOCATABLE, TARGET, SAVE :: N_PARTICLE_BINS_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: AGGLOMERATION_SPEC_INDEX_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: AGGLOMERATION_SMIX_INDEX_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: MIN_PARTICLE_DIAMETER_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: MAX_PARTICLE_DIAMETER_TMP(:)


REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_AWM_AEROSOL_FLAT(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: BP1_ZZ_G_FLAT(:)

REAL(EB), ALLOCATABLE, TARGET, SAVE :: NU_SOOT_OX_TMP(:)

REAL(EB), ALLOCATABLE, TARGET, SAVE :: D_Z_FLAT(:)

REAL(EB), ALLOCATABLE, TARGET, SAVE :: CELL_SOLID_TMP(:)

REAL(EB), ALLOCATABLE, TARGET, SAVE :: LP_U_TMP(:), LP_V_TMP(:), LP_W_TMP(:)
REAL(EB), ALLOCATABLE, TARGET, SAVE :: LP_RADIUS_TMP(:), LP_RVC_TMP(:), LP_PWT_TMP(:)
INTEGER, ALLOCATABLE, TARGET, SAVE :: LP_BC_INDEX_TMP(:), LP_B1_INDEX_TMP(:)

LOGICAL, SAVE :: ARRAYS_ALLOCATED = .FALSE.
INTEGER, SAVE :: PREV_NTS = -1, PREV_NW = -1, PREV_NICF = -1
INTEGER, SAVE :: PREV_NA = -1, PREV_NSPEC = -1, PREV_NC = -1

! ---------------------------------------------------------------------------
! extern "C" 桥接函数接口 (Fortran → C++)
! ---------------------------------------------------------------------------
INTERFACE
  SUBROUTINE soot_c_initialize_agglomeration(mp) BIND(C)
    IMPORT :: SOOT_MP_C
    TYPE(SOOT_MP_C), INTENT(IN) :: mp
  END SUBROUTINE
  SUBROUTINE soot_c_settling_velocity(mp) BIND(C)
    IMPORT :: SOOT_MP_C
    TYPE(SOOT_MP_C), INTENT(IN) :: mp
  END SUBROUTINE
  SUBROUTINE soot_c_calc_agglomeration(DT, mp) BIND(C)
    USE ISO_C_BINDING, ONLY: C_DOUBLE
    IMPORT :: SOOT_MP_C
    REAL(C_DOUBLE), VALUE :: DT
    TYPE(SOOT_MP_C), INTENT(IN) :: mp
  END SUBROUTINE
  SUBROUTINE soot_c_soot_surface_oxidation(DT, mp) BIND(C)
    USE ISO_C_BINDING, ONLY: C_DOUBLE
    IMPORT :: SOOT_MP_C
    REAL(C_DOUBLE), VALUE :: DT
    TYPE(SOOT_MP_C), INTENT(IN) :: mp
  END SUBROUTINE
  SUBROUTINE soot_c_droplet_scrubbing(IP, DT, DT_P, mp) BIND(C)
    USE ISO_C_BINDING, ONLY: C_DOUBLE, C_INT
    IMPORT :: SOOT_MP_C
    INTEGER(C_INT), VALUE :: IP
    REAL(C_DOUBLE), VALUE :: DT, DT_P
    TYPE(SOOT_MP_C), INTENT(IN) :: mp
  END SUBROUTINE
  FUNCTION soot_c_n_agglomeration_species() BIND(C)
    USE ISO_C_BINDING, ONLY: C_INT
    INTEGER(C_INT) :: soot_c_n_agglomeration_species
  END FUNCTION
  FUNCTION soot_c_max_particle_bins() BIND(C)
    USE ISO_C_BINDING, ONLY: C_INT
    INTEGER(C_INT) :: soot_c_max_particle_bins
  END FUNCTION
  FUNCTION soot_c_particle_radius(sp, bin) BIND(C)
    USE ISO_C_BINDING, ONLY: C_DOUBLE, C_INT
    INTEGER(C_INT), VALUE :: sp, bin
    REAL(C_DOUBLE) :: soot_c_particle_radius
  END FUNCTION
END INTERFACE

CONTAINS

SUBROUTINE ENSURE_SM(NTS)
  INTEGER, INTENT(IN) :: NTS
  IF (ARRAYS_ALLOCATED .AND. NTS == PREV_NTS) RETURN
  IF (ALLOCATED(SM_DEPOSITING_TMP)) DEALLOCATE(SM_DEPOSITING_TMP,SM_MEAN_DIAMETER_TMP,&
    SM_DENSITY_SOLID_TMP,SM_THERMOPHORETIC_DIAMETER_TMP,SM_CONDUCTIVITY_SOLID_TMP,&
    SM_H_F_TMP,SM_RCON_TMP,SM_MW_TMP,SM_AWM_INDEX_TMP,SM_AGGLOMERATION_INDEX_TMP)
  ALLOCATE(SM_DEPOSITING_TMP(NTS),SM_MEAN_DIAMETER_TMP(NTS),SM_DENSITY_SOLID_TMP(NTS),&
    SM_THERMOPHORETIC_DIAMETER_TMP(NTS),SM_CONDUCTIVITY_SOLID_TMP(NTS),&
    SM_H_F_TMP(NTS),SM_RCON_TMP(NTS),SM_MW_TMP(NTS),&
    SM_AWM_INDEX_TMP(NTS),SM_AGGLOMERATION_INDEX_TMP(NTS))
  PREV_NTS = NTS
END SUBROUTINE ENSURE_SM

SUBROUTINE ENSURE_SP(NSPEC)
  INTEGER, INTENT(IN) :: NSPEC
  IF (ARRAYS_ALLOCATED .AND. NSPEC == PREV_NSPEC) RETURN
  IF (ALLOCATED(SP_DENSITY_SOLID_TMP)) DEALLOCATE(SP_DENSITY_SOLID_TMP,SP_CONDUCTIVITY_SOLID_TMP,&
    SP_AWM_INDEX_TMP,SP_AGGLOMERATING_TMP)
  ALLOCATE(SP_DENSITY_SOLID_TMP(NSPEC),SP_CONDUCTIVITY_SOLID_TMP(NSPEC),&
    SP_AWM_INDEX_TMP(NSPEC),SP_AGGLOMERATING_TMP(NSPEC))
  PREV_NSPEC = NSPEC
END SUBROUTINE ENSURE_SP

SUBROUTINE ENSURE_WALL(NW)
  INTEGER, INTENT(IN) :: NW
  IF (ARRAYS_ALLOCATED .AND. NW == PREV_NW) RETURN
  IF (ALLOCATED(WALL_BC_TYPE_TMP)) DEALLOCATE(WALL_BC_TYPE_TMP,WALL_BC_INDEX_TMP,&
    WALL_B1_INDEX_TMP,BC_IIG_TMP,BC_JJG_TMP,BC_KKG_TMP,BC_IOR_TMP,&
    BP1_AREA_TMP,BP1_TMP_F_TMP,BP1_RHO_G_TMP,BP1_TMP_G_TMP,&
    BP1_AWM_AEROSOL_TMP,BP1_ZZ_G_TMP)
  ALLOCATE(WALL_BC_TYPE_TMP(NW),WALL_BC_INDEX_TMP(NW),WALL_B1_INDEX_TMP(NW),&
    BC_IIG_TMP(NW),BC_JJG_TMP(NW),BC_KKG_TMP(NW),BC_IOR_TMP(NW),&
    BP1_AREA_TMP(NW),BP1_TMP_F_TMP(NW),BP1_RHO_G_TMP(NW),BP1_TMP_G_TMP(NW),&
    BP1_AWM_AEROSOL_TMP(NW),BP1_ZZ_G_TMP(NW))
  PREV_NW = NW
END SUBROUTINE ENSURE_WALL

SUBROUTINE ENSURE_CFACE(NICF)
  INTEGER, INTENT(IN) :: NICF
  IF (ARRAYS_ALLOCATED .AND. NICF == PREV_NICF) RETURN
  IF (ALLOCATED(CFACE_BC_TYPE_TMP)) DEALLOCATE(CFACE_BC_TYPE_TMP,CFACE_B1_INDEX_TMP,&
    CFACE_BC_INDEX_TMP,CFACE_RSUM_G_TMP)
  ALLOCATE(CFACE_BC_TYPE_TMP(NICF),CFACE_B1_INDEX_TMP(NICF),&
    CFACE_BC_INDEX_TMP(NICF),CFACE_RSUM_G_TMP(NICF))
  PREV_NICF = NICF
END SUBROUTINE ENSURE_CFACE

SUBROUTINE ENSURE_AGGL_CONFIG(NA)
  INTEGER, INTENT(IN) :: NA
  IF (ARRAYS_ALLOCATED .AND. NA == PREV_NA) RETURN
  IF (ALLOCATED(N_PARTICLE_BINS_TMP)) DEALLOCATE(N_PARTICLE_BINS_TMP,&
    AGGLOMERATION_SPEC_INDEX_TMP,AGGLOMERATION_SMIX_INDEX_TMP,&
    MIN_PARTICLE_DIAMETER_TMP,MAX_PARTICLE_DIAMETER_TMP)
  ALLOCATE(N_PARTICLE_BINS_TMP(NA),AGGLOMERATION_SPEC_INDEX_TMP(NA),&
    AGGLOMERATION_SMIX_INDEX_TMP(NA),MIN_PARTICLE_DIAMETER_TMP(NA),&
    MAX_PARTICLE_DIAMETER_TMP(NA))
  PREV_NA = NA
END SUBROUTINE ENSURE_AGGL_CONFIG

SUBROUTINE ENSURE_CELL(NC)
  INTEGER, INTENT(IN) :: NC
  IF (ARRAYS_ALLOCATED .AND. NC == PREV_NC) RETURN
  IF (ALLOCATED(CELL_SOLID_TMP)) DEALLOCATE(CELL_SOLID_TMP)
  ALLOCATE(CELL_SOLID_TMP(NC))
  PREV_NC = NC
END SUBROUTINE ENSURE_CELL


SUBROUTINE FILL_SM_ARRAYS(NTS)
  INTEGER, INTENT(IN) :: NTS
  INTEGER :: I
  CALL ENSURE_SM(NTS)
  DO I = 1, NTS
    SM_DEPOSITING_TMP(I)          = MERGE(1.0_EB, 0.0_EB, SPECIES_MIXTURE(I)%DEPOSITING)
    SM_MEAN_DIAMETER_TMP(I)       = SPECIES_MIXTURE(I)%MEAN_DIAMETER
    SM_DENSITY_SOLID_TMP(I)       = SPECIES_MIXTURE(I)%DENSITY_SOLID
    SM_THERMOPHORETIC_DIAMETER_TMP(I) = SPECIES_MIXTURE(I)%THERMOPHORETIC_DIAMETER
    SM_CONDUCTIVITY_SOLID_TMP(I)  = SPECIES_MIXTURE(I)%CONDUCTIVITY_SOLID
    SM_H_F_TMP(I)                 = SPECIES_MIXTURE(I)%H_F
    SM_RCON_TMP(I)                = SPECIES_MIXTURE(I)%RCON
    SM_MW_TMP(I)                  = SPECIES_MIXTURE(I)%MW
    SM_AWM_INDEX_TMP(I)           = SPECIES_MIXTURE(I)%AWM_INDEX
    SM_AGGLOMERATION_INDEX_TMP(I) = SPECIES_MIXTURE(I)%AGGLOMERATION_INDEX
  ENDDO
END SUBROUTINE FILL_SM_ARRAYS

SUBROUTINE FILL_SP_ARRAYS(NSPEC)
  INTEGER, INTENT(IN) :: NSPEC
  INTEGER :: I
  CALL ENSURE_SP(NSPEC)
  DO I = 1, NSPEC
    SP_DENSITY_SOLID_TMP(I)     = SPECIES(I)%DENSITY_SOLID
    SP_CONDUCTIVITY_SOLID_TMP(I)= SPECIES(I)%CONDUCTIVITY_SOLID
    SP_AWM_INDEX_TMP(I)         = SPECIES(I)%AWM_INDEX
    SP_AGGLOMERATING_TMP(I)     = MERGE(1.0_EB, 0.0_EB, SPECIES(I)%AGGLOMERATING)
  ENDDO
END SUBROUTINE FILL_SP_ARRAYS

SUBROUTINE FILL_AGGL_CONFIG(NA)
  INTEGER, INTENT(IN) :: NA
  INTEGER :: I
  CALL ENSURE_AGGL_CONFIG(NA)
  DO I = 1, NA
    N_PARTICLE_BINS_TMP(I)         = N_PARTICLE_BINS(I)
    AGGLOMERATION_SPEC_INDEX_TMP(I)= AGGLOMERATION_SPEC_INDEX(I)
    AGGLOMERATION_SMIX_INDEX_TMP(I)= AGGLOMERATION_SMIX_INDEX(I)
    MIN_PARTICLE_DIAMETER_TMP(I)   = MIN_PARTICLE_DIAMETER(I)
    MAX_PARTICLE_DIAMETER_TMP(I)   = MAX_PARTICLE_DIAMETER(I)
  ENDDO
END SUBROUTINE FILL_AGGL_CONFIG


SUBROUTINE PACK_MP_C(mp)
  TYPE(SOOT_MP_C), INTENT(OUT) :: mp
  INTEGER :: I, J, K, IC, IW, NC, NTS, NSPEC, NA, NW, NICF
  TYPE(WALL_TYPE), POINTER :: WC
  TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
  TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1
  TYPE(CFACE_TYPE), POINTER :: CFA

  mp%U = C_LOC(U(LBOUND(U,1),LBOUND(U,2),LBOUND(U,3)))
  mp%V = C_LOC(V(LBOUND(V,1),LBOUND(V,2),LBOUND(V,3)))
  mp%W = C_LOC(W(LBOUND(W,1),LBOUND(W,2),LBOUND(W,3)))
  mp%RHO   = C_LOC(RHO(LBOUND(RHO,1),LBOUND(RHO,2),LBOUND(RHO,3)))
  mp%RHOS  = C_LOC(RHOS(LBOUND(RHOS,1),LBOUND(RHOS,2),LBOUND(RHOS,3)))
  mp%TMP   = C_LOC(TMP(LBOUND(TMP,1),LBOUND(TMP,2),LBOUND(TMP,3)))
  mp%MU    = C_LOC(MU(LBOUND(MU,1),LBOUND(MU,2),LBOUND(MU,3)))
  mp%Q     = C_LOC(Q(LBOUND(Q,1),LBOUND(Q,2),LBOUND(Q,3)))
  mp%D_SOURCE = C_LOC(D_SOURCE(LBOUND(D_SOURCE,1),LBOUND(D_SOURCE,2),LBOUND(D_SOURCE,3)))
  mp%RSUM  = C_LOC(RSUM(LBOUND(RSUM,1),LBOUND(RSUM,2),LBOUND(RSUM,3)))
  mp%ZZ  = C_LOC(ZZ(LBOUND(ZZ,1),LBOUND(ZZ,2),LBOUND(ZZ,3),LBOUND(ZZ,4)))
  mp%ZZS = C_LOC(ZZS(LBOUND(ZZS,1),LBOUND(ZZS,2),LBOUND(ZZS,3),LBOUND(ZZS,4)))
  mp%DEL_RHO_D_DEL_Z = C_LOC(DEL_RHO_D_DEL_Z(LBOUND(DEL_RHO_D_DEL_Z,1),&
    LBOUND(DEL_RHO_D_DEL_Z,2),LBOUND(DEL_RHO_D_DEL_Z,3),LBOUND(DEL_RHO_D_DEL_Z,4)))
  mp%FX = C_LOC(FX(LBOUND(FX,1),LBOUND(FX,2),LBOUND(FX,3),LBOUND(FX,4)))
  mp%FY = C_LOC(FY(LBOUND(FY,1),LBOUND(FY,2),LBOUND(FY,3),LBOUND(FY,4)))
  mp%FZ = C_LOC(FZ(LBOUND(FZ,1),LBOUND(FZ,2),LBOUND(FZ,3),LBOUND(FZ,4)))
  mp%M_DOT_PPP = C_LOC(M_DOT_PPP(LBOUND(M_DOT_PPP,1),LBOUND(M_DOT_PPP,2),&
    LBOUND(M_DOT_PPP,3),LBOUND(M_DOT_PPP,4)))
  mp%R    = C_LOC(R(LBOUND(R,1)));   mp%RC   = C_LOC(RC(LBOUND(RC,1)))
  mp%RRN  = C_LOC(RRN(LBOUND(RRN,1)))
  mp%DX   = C_LOC(DX(LBOUND(DX,1))); mp%RDX  = C_LOC(RDX(LBOUND(RDX,1)))
  mp%RDXN = C_LOC(RDXN(LBOUND(RDXN,1)))
  mp%DY   = C_LOC(DY(LBOUND(DY,1))); mp%RDY  = C_LOC(RDY(LBOUND(RDY,1)))
  mp%DYN  = C_LOC(DYN(LBOUND(DYN,1))); mp%RDYN = C_LOC(RDYN(LBOUND(RDYN,1)))
  mp%DZ   = C_LOC(DZ(LBOUND(DZ,1))); mp%RDZ  = C_LOC(RDZ(LBOUND(RDZ,1)))
  mp%DZN  = C_LOC(DZN(LBOUND(DZN,1))); mp%RDZN = C_LOC(RDZN(LBOUND(RDZN,1)))
  mp%PBAR = C_LOC(PBAR(LBOUND(PBAR,1),LBOUND(PBAR,2)))
  mp%PRESSURE_ZONE = C_LOC(PRESSURE_ZONE(LBOUND(PRESSURE_ZONE,1),LBOUND(PRESSURE_ZONE,2),LBOUND(PRESSURE_ZONE,3)))
  mp%CELL_INDEX = C_LOC(CELL_INDEX(LBOUND(CELL_INDEX,1),LBOUND(CELL_INDEX,2),LBOUND(CELL_INDEX,3)))
  mp%IBAR = IBAR; mp%JBAR = JBAR; mp%KBAR = KBAR
  mp%N_EXTERNAL_WALL_CELLS = N_EXTERNAL_WALL_CELLS
  mp%N_INTERNAL_WALL_CELLS = N_INTERNAL_WALL_CELLS
  mp%INTERNAL_CFACE_CELLS_LB = INTERNAL_CFACE_CELLS_LB
  mp%N_INTERNAL_CFACE_CELLS = N_INTERNAL_CFACE_CELLS
  mp%N_SPECIES = SIZE(SPECIES)
  mp%PREDICTOR_FLAG = MERGE(1, 0, PREDICTOR)
  NTS = N_TRACKED_SPECIES
  mp%N_TRACKED_SPECIES = NTS
  mp%GVEC_X = GVEC(1); mp%GVEC_Y = GVEC(2); mp%GVEC_Z = GVEC(3)
  mp%NULL_BOUNDARY_VAL = NULL_BOUNDARY
  mp%OPEN_BOUNDARY_VAL = OPEN_BOUNDARY
  mp%INTERPOLATED_BOUNDARY_VAL = INTERPOLATED_BOUNDARY
  NA = N_AGGLOMERATION_SPECIES
  mp%N_AGGLOMERATION_SPECIES = NA
  mp%SOOT_INDEX = SOOT_INDEX; mp%O2_INDEX = O2_INDEX
  mp%N_SURFACE_DENSITY_SPECIES = N_SURFACE_DENSITY_SPECIES
  mp%R0_VAL = R0; mp%MW_O2_VAL = MW_O2
  mp%ZZ_MIN_GLOBAL_VAL = ZZ_MIN_GLOBAL

  IF (ALLOCATED(NU_SOOT_OX_TMP)) DEALLOCATE(NU_SOOT_OX_TMP)
  ALLOCATE(NU_SOOT_OX_TMP(NTS))
  NU_SOOT_OX_TMP(1:NTS) = NU_SOOT_OX(1:NTS)
  mp%NU_SOOT_OX = C_LOC(NU_SOOT_OX_TMP(1))
  mp%I_MAX_TEMP_VAL = I_MAX_TEMP
  mp%N_TOTAL_SCALARS_VAL = N_TRACKED_SPECIES

  CALL FILL_SM_ARRAYS(NTS)
  mp%SM_DEPOSITING          = C_LOC(SM_DEPOSITING_TMP(1))
  mp%SM_MEAN_DIAMETER       = C_LOC(SM_MEAN_DIAMETER_TMP(1))
  mp%SM_DENSITY_SOLID       = C_LOC(SM_DENSITY_SOLID_TMP(1))
  mp%SM_THERMOPHORETIC_DIAMETER = C_LOC(SM_THERMOPHORETIC_DIAMETER_TMP(1))
  mp%SM_CONDUCTIVITY_SOLID  = C_LOC(SM_CONDUCTIVITY_SOLID_TMP(1))
  mp%SM_H_F                 = C_LOC(SM_H_F_TMP(1))
  mp%SM_RCON                = C_LOC(SM_RCON_TMP(1))
  mp%SM_MW                  = C_LOC(SM_MW_TMP(1))
  mp%SM_AWM_INDEX           = C_LOC(SM_AWM_INDEX_TMP(1))
  mp%SM_AGGLOMERATION_INDEX = C_LOC(SM_AGGLOMERATION_INDEX_TMP(1))

  NSPEC = SIZE(SPECIES)
  CALL FILL_SP_ARRAYS(NSPEC)
  mp%SP_DENSITY_SOLID      = C_LOC(SP_DENSITY_SOLID_TMP(1))
  mp%SP_CONDUCTIVITY_SOLID = C_LOC(SP_CONDUCTIVITY_SOLID_TMP(1))
  mp%SP_AWM_INDEX          = C_LOC(SP_AWM_INDEX_TMP(1))
  mp%SP_AGGLOMERATING      = C_LOC(SP_AGGLOMERATING_TMP(1))

  CALL FILL_AGGL_CONFIG(NA)
  mp%N_PARTICLE_BINS         = C_LOC(N_PARTICLE_BINS_TMP(1))
  mp%AGGLOMERATION_SPEC_INDEX= C_LOC(AGGLOMERATION_SPEC_INDEX_TMP(1))
  mp%AGGLOMERATION_SMIX_INDEX= C_LOC(AGGLOMERATION_SMIX_INDEX_TMP(1))
  mp%MIN_PARTICLE_DIAMETER   = C_LOC(MIN_PARTICLE_DIAMETER_TMP(1))
  mp%MAX_PARTICLE_DIAMETER   = C_LOC(MAX_PARTICLE_DIAMETER_TMP(1))

  NW = N_EXTERNAL_WALL_CELLS + N_INTERNAL_WALL_CELLS
  CALL ENSURE_WALL(NW)
  DO IW = 1, NW
    WC => WALL(IW)
    BC => BOUNDARY_COORD(WC%BC_INDEX)
    B1 => BOUNDARY_PROP1(WC%B1_INDEX)
    WALL_BC_TYPE_TMP(IW)  = WC%BOUNDARY_TYPE
    WALL_BC_INDEX_TMP(IW) = WC%BC_INDEX
    WALL_B1_INDEX_TMP(IW) = WC%B1_INDEX
    BC_IIG_TMP(IW) = BC%IIG; BC_JJG_TMP(IW) = BC%JJG
    BC_KKG_TMP(IW) = BC%KKG; BC_IOR_TMP(IW) = BC%IOR
    BP1_AREA_TMP(IW)   = B1%AREA
    BP1_TMP_F_TMP(IW)  = B1%TMP_F
    BP1_RHO_G_TMP(IW)  = B1%RHO_G
    BP1_TMP_G_TMP(IW)  = B1%TMP_G
  ENDDO
  mp%WALL_BC_TYPE      = C_LOC(WALL_BC_TYPE_TMP(1))
  mp%WALL_BC_INDEX     = C_LOC(WALL_BC_INDEX_TMP(1))
  mp%WALL_B1_INDEX     = C_LOC(WALL_B1_INDEX_TMP(1))
  mp%BC_IIG            = C_LOC(BC_IIG_TMP(1))
  mp%BC_JJG            = C_LOC(BC_JJG_TMP(1))
  mp%BC_KKG            = C_LOC(BC_KKG_TMP(1))
  mp%BC_IOR            = C_LOC(BC_IOR_TMP(1))
  mp%BP1_AREA          = C_LOC(BP1_AREA_TMP(1))
  mp%BP1_TMP_F         = C_LOC(BP1_TMP_F_TMP(1))
  mp%BP1_RHO_G         = C_LOC(BP1_RHO_G_TMP(1))
  mp%BP1_TMP_G         = C_LOC(BP1_TMP_G_TMP(1))


  IF (ALLOCATED(BP1_AWM_AEROSOL_FLAT)) DEALLOCATE(BP1_AWM_AEROSOL_FLAT)
  IF (N_SURFACE_DENSITY_SPECIES > 0 .AND. NW > 0) THEN
    ALLOCATE(BP1_AWM_AEROSOL_FLAT(NW * N_SURFACE_DENSITY_SPECIES))
    DO IW = 1, NW
      WC => WALL(IW)
      B1 => BOUNDARY_PROP1(WC%B1_INDEX)
      BP1_AWM_AEROSOL_FLAT((IW-1)*N_SURFACE_DENSITY_SPECIES+1 : IW*N_SURFACE_DENSITY_SPECIES) = &
        B1%AWM_AEROSOL(1:N_SURFACE_DENSITY_SPECIES)
    ENDDO
    mp%BP1_AWM_AEROSOL = C_LOC(BP1_AWM_AEROSOL_FLAT(1))
  ELSE
    mp%BP1_AWM_AEROSOL = C_NULL_PTR
  ENDIF


  IF (ALLOCATED(BP1_ZZ_G_FLAT)) DEALLOCATE(BP1_ZZ_G_FLAT)
  IF (NTS > 0 .AND. NW > 0) THEN
    ALLOCATE(BP1_ZZ_G_FLAT(NW * NTS))
    DO IW = 1, NW
      WC => WALL(IW)
      B1 => BOUNDARY_PROP1(WC%B1_INDEX)
      BP1_ZZ_G_FLAT((IW-1)*NTS+1 : IW*NTS) = B1%ZZ_G(1:NTS)
    ENDDO
    mp%BP1_ZZ_G = C_LOC(BP1_ZZ_G_FLAT(1))
  ELSE
    mp%BP1_ZZ_G = C_NULL_PTR
  ENDIF

  NICF = N_INTERNAL_CFACE_CELLS
  CALL ENSURE_CFACE(NICF)
  DO IW = 1, NICF
    CFA => CFACE(INTERNAL_CFACE_CELLS_LB + IW)
    CFACE_BC_TYPE_TMP(IW)  = CFA%BOUNDARY_TYPE
    CFACE_B1_INDEX_TMP(IW) = CFA%B1_INDEX
    CFACE_BC_INDEX_TMP(IW) = CFA%BC_INDEX
    CFACE_RSUM_G_TMP(IW)   = CFA%RSUM_G
  ENDDO
  mp%CFACE_BC_TYPE  = C_LOC(CFACE_BC_TYPE_TMP(1))
  mp%CFACE_B1_INDEX = C_LOC(CFACE_B1_INDEX_TMP(1))
  mp%CFACE_BC_INDEX = C_LOC(CFACE_BC_INDEX_TMP(1))
  mp%CFACE_RSUM_G   = C_LOC(CFACE_RSUM_G_TMP(1))

  NC = (IBAR+1)*(JBAR+1)*(KBAR+1)
  CALL ENSURE_CELL(NC)
  CELL_SOLID_TMP(:) = 0.0_EB
  DO K = 0, KBAR
    DO J = 0, JBAR
      DO I = 0, IBAR
        IC = CELL_INDEX(I, J, K)
        IF (IC > 0) THEN
          CELL_SOLID_TMP(IC) = MERGE(1.0_EB, 0.0_EB, CELL(IC)%SOLID)
        ENDIF
      ENDDO
    ENDDO
  ENDDO

  mp%WORK7 = C_LOC(WORK7(LBOUND(WORK7,1),LBOUND(WORK7,2),LBOUND(WORK7,3)))
  mp%WORK8 = C_LOC(WORK8(LBOUND(WORK8,1),LBOUND(WORK8,2),LBOUND(WORK8,3)))
  mp%WORK9 = C_LOC(WORK9(LBOUND(WORK9,1),LBOUND(WORK9,2),LBOUND(WORK9,3)))

  mp%LP_U = C_NULL_PTR; mp%LP_V = C_NULL_PTR; mp%LP_W = C_NULL_PTR
  mp%LP_RADIUS = C_NULL_PTR; mp%LP_RVC = C_NULL_PTR; mp%LP_PWT = C_NULL_PTR
  mp%LP_BC_INDEX = C_NULL_PTR; mp%LP_B1_INDEX = C_NULL_PTR
  mp%LP_U_VAL = 0.0_C_DOUBLE; mp%LP_V_VAL = 0.0_C_DOUBLE; mp%LP_W_VAL = 0.0_C_DOUBLE
  mp%LP_RADIUS_VAL = 0.0_C_DOUBLE; mp%LP_RVC_VAL = 0.0_C_DOUBLE; mp%LP_PWT_VAL = 0.0_C_DOUBLE
  mp%LP_BC_INDEX_VAL = 0; mp%LP_B1_INDEX_VAL = 0
  mp%LP_IIG_VAL = 0; mp%LP_JJG_VAL = 0; mp%LP_KKG_VAL = 0
  mp%LP_BP1_AREA_VAL = 0.0_C_DOUBLE; mp%LP_BP1_TMP_F_VAL = 0.0_C_DOUBLE
  mp%LP_BP1_RHO_G_VAL = 0.0_C_DOUBLE; mp%LP_BP1_TMP_G_VAL = 0.0_C_DOUBLE

  IF (ALLOCATED(D_Z_FLAT)) DEALLOCATE(D_Z_FLAT)
  IF (I_MAX_TEMP > 0 .AND. N_TRACKED_SPECIES > 0) THEN
    ALLOCATE(D_Z_FLAT((I_MAX_TEMP+1) * N_TRACKED_SPECIES))
    D_Z_FLAT(1:) = PACK(D_Z(0:I_MAX_TEMP, 1:N_TRACKED_SPECIES), .TRUE.)
    mp%D_Z_PTR = C_LOC(D_Z_FLAT(1))
  ELSE
    mp%D_Z_PTR = C_NULL_PTR
  ENDIF

  ARRAYS_ALLOCATED = .TRUE.
END SUBROUTINE PACK_MP_C


SUBROUTINE PACK_GLOBALS_ONLY(mp)
 TYPE(SOOT_MP_C), INTENT(OUT) :: mp
 INTEGER :: NTS, NA, NSPEC

 mp%U = C_NULL_PTR; mp%V = C_NULL_PTR; mp%W = C_NULL_PTR
 mp%RHO = C_NULL_PTR; mp%RHOS = C_NULL_PTR; mp%TMP = C_NULL_PTR; mp%MU = C_NULL_PTR
 mp%Q = C_NULL_PTR; mp%D_SOURCE = C_NULL_PTR; mp%RSUM = C_NULL_PTR
 mp%ZZ = C_NULL_PTR; mp%ZZS = C_NULL_PTR; mp%DEL_RHO_D_DEL_Z = C_NULL_PTR
 mp%FX = C_NULL_PTR; mp%FY = C_NULL_PTR; mp%FZ = C_NULL_PTR; mp%M_DOT_PPP = C_NULL_PTR
 mp%R = C_NULL_PTR; mp%RC = C_NULL_PTR; mp%RRN = C_NULL_PTR
 mp%DX = C_NULL_PTR; mp%RDX = C_NULL_PTR; mp%RDXN = C_NULL_PTR
 mp%DY = C_NULL_PTR; mp%RDY = C_NULL_PTR; mp%DYN = C_NULL_PTR; mp%RDYN = C_NULL_PTR
 mp%DZ = C_NULL_PTR; mp%RDZ = C_NULL_PTR; mp%DZN = C_NULL_PTR; mp%RDZN = C_NULL_PTR
 mp%PBAR = C_NULL_PTR; mp%PRESSURE_ZONE = C_NULL_PTR; mp%CELL_INDEX = C_NULL_PTR
 mp%IBAR = 0; mp%JBAR = 0; mp%KBAR = 0
 mp%N_EXTERNAL_WALL_CELLS = 0; mp%N_INTERNAL_WALL_CELLS = 0
 mp%INTERNAL_CFACE_CELLS_LB = 0; mp%N_INTERNAL_CFACE_CELLS = 0
 mp%N_SPECIES = SIZE(SPECIES)
 mp%PREDICTOR_FLAG = MERGE(1, 0, PREDICTOR)
 NTS = N_TRACKED_SPECIES
 mp%N_TRACKED_SPECIES = NTS
 mp%GVEC_X = GVEC(1); mp%GVEC_Y = GVEC(2); mp%GVEC_Z = GVEC(3)
 mp%NULL_BOUNDARY_VAL = NULL_BOUNDARY
 mp%OPEN_BOUNDARY_VAL = OPEN_BOUNDARY
 mp%INTERPOLATED_BOUNDARY_VAL = INTERPOLATED_BOUNDARY
 NA = N_AGGLOMERATION_SPECIES
 mp%N_AGGLOMERATION_SPECIES = NA
 mp%SOOT_INDEX = SOOT_INDEX; mp%O2_INDEX = O2_INDEX
 mp%N_SURFACE_DENSITY_SPECIES = N_SURFACE_DENSITY_SPECIES
 mp%R0_VAL = R0; mp%MW_O2_VAL = MW_O2
 mp%ZZ_MIN_GLOBAL_VAL = ZZ_MIN_GLOBAL
 mp%NU_SOOT_OX = C_NULL_PTR
 mp%I_MAX_TEMP_VAL = I_MAX_TEMP
 mp%N_TOTAL_SCALARS_VAL = N_TRACKED_SPECIES

 CALL FILL_SM_ARRAYS(NTS)
 mp%SM_DEPOSITING          = C_LOC(SM_DEPOSITING_TMP(1))
 mp%SM_MEAN_DIAMETER       = C_LOC(SM_MEAN_DIAMETER_TMP(1))
 mp%SM_DENSITY_SOLID       = C_LOC(SM_DENSITY_SOLID_TMP(1))
 mp%SM_THERMOPHORETIC_DIAMETER = C_LOC(SM_THERMOPHORETIC_DIAMETER_TMP(1))
 mp%SM_CONDUCTIVITY_SOLID  = C_LOC(SM_CONDUCTIVITY_SOLID_TMP(1))
 mp%SM_H_F                 = C_LOC(SM_H_F_TMP(1))
 mp%SM_RCON                = C_LOC(SM_RCON_TMP(1))
 mp%SM_MW                  = C_LOC(SM_MW_TMP(1))
 mp%SM_AWM_INDEX           = C_LOC(SM_AWM_INDEX_TMP(1))
 mp%SM_AGGLOMERATION_INDEX = C_LOC(SM_AGGLOMERATION_INDEX_TMP(1))

 NSPEC = SIZE(SPECIES)
 CALL FILL_SP_ARRAYS(NSPEC)
 mp%SP_DENSITY_SOLID      = C_LOC(SP_DENSITY_SOLID_TMP(1))
 mp%SP_CONDUCTIVITY_SOLID = C_LOC(SP_CONDUCTIVITY_SOLID_TMP(1))
 mp%SP_AWM_INDEX          = C_LOC(SP_AWM_INDEX_TMP(1))
 mp%SP_AGGLOMERATING      = C_LOC(SP_AGGLOMERATING_TMP(1))

 CALL FILL_AGGL_CONFIG(NA)
 mp%N_PARTICLE_BINS         = C_LOC(N_PARTICLE_BINS_TMP(1))
 mp%AGGLOMERATION_SPEC_INDEX= C_LOC(AGGLOMERATION_SPEC_INDEX_TMP(1))
 mp%AGGLOMERATION_SMIX_INDEX= C_LOC(AGGLOMERATION_SMIX_INDEX_TMP(1))
 mp%MIN_PARTICLE_DIAMETER   = C_LOC(MIN_PARTICLE_DIAMETER_TMP(1))
 mp%MAX_PARTICLE_DIAMETER   = C_LOC(MAX_PARTICLE_DIAMETER_TMP(1))

 mp%WALL_BC_TYPE = C_NULL_PTR
 mp%CFACE_BC_TYPE = C_NULL_PTR
 mp%CELL_SOLID = C_NULL_PTR
 mp%WORK7 = C_NULL_PTR; mp%WORK8 = C_NULL_PTR; mp%WORK9 = C_NULL_PTR
 mp%LP_U = C_NULL_PTR; mp%LP_V = C_NULL_PTR; mp%LP_W = C_NULL_PTR
 mp%LP_RADIUS = C_NULL_PTR; mp%LP_RVC = C_NULL_PTR; mp%LP_PWT = C_NULL_PTR
 mp%LP_BC_INDEX = C_NULL_PTR; mp%LP_B1_INDEX = C_NULL_PTR
 mp%LP_U_VAL = 0.0_C_DOUBLE; mp%LP_V_VAL = 0.0_C_DOUBLE; mp%LP_W_VAL = 0.0_C_DOUBLE
 mp%LP_RADIUS_VAL = 0.0_C_DOUBLE; mp%LP_RVC_VAL = 0.0_C_DOUBLE; mp%LP_PWT_VAL = 0.0_C_DOUBLE
 mp%LP_BC_INDEX_VAL = 0; mp%LP_B1_INDEX_VAL = 0
 mp%LP_IIG_VAL = 0; mp%LP_JJG_VAL = 0; mp%LP_KKG_VAL = 0
 mp%LP_BP1_AREA_VAL = 0.0_C_DOUBLE; mp%LP_BP1_TMP_F_VAL = 0.0_C_DOUBLE
 mp%LP_BP1_RHO_G_VAL = 0.0_C_DOUBLE; mp%LP_BP1_TMP_G_VAL = 0.0_C_DOUBLE

 mp%D_Z_PTR = C_NULL_PTR
END SUBROUTINE PACK_GLOBALS_ONLY

! ===========================================================================
! SETTLING_VELOCITY — 重力沉降 + 热泳 (Fortran 兼容接口)
! ===========================================================================
SUBROUTINE SETTLING_VELOCITY(NM)
 INTEGER, INTENT(IN) :: NM
 TYPE(SOOT_MP_C) :: mp
 CALL POINT_TO_MESH(NM)
 CALL PACK_MP_C(mp)
 CALL soot_c_settling_velocity(mp)
END SUBROUTINE SETTLING_VELOCITY

! ===========================================================================
! CALC_AGGLOMERATION — 团聚主计算
! ===========================================================================
SUBROUTINE CALC_AGGLOMERATION(DT,NM)
 REAL(EB), INTENT(IN) :: DT
 INTEGER, INTENT(IN) :: NM
 TYPE(SOOT_MP_C) :: mp
 CALL POINT_TO_MESH(NM)
 CALL PACK_MP_C(mp)
 CALL soot_c_calc_agglomeration(REAL(DT,C_DOUBLE), mp)
END SUBROUTINE CALC_AGGLOMERATION

! ===========================================================================
! INITIALIZE_AGGLOMERATION — 初始化粒子箱和团聚核（无网格依赖，仅全局常量）
! ===========================================================================
SUBROUTINE INITIALIZE_AGGLOMERATION
 TYPE(SOOT_MP_C) :: mp
 CALL PACK_GLOBALS_ONLY(mp)
 CALL soot_c_initialize_agglomeration(mp)
END SUBROUTINE INITIALIZE_AGGLOMERATION

! ===========================================================================
! SOOT_SURFACE_OXIDATION — 壁面积碳氧化
! ===========================================================================
SUBROUTINE SOOT_SURFACE_OXIDATION(DT,NM)
 REAL(EB), INTENT(IN) :: DT
 INTEGER, INTENT(IN) :: NM
 TYPE(SOOT_MP_C) :: mp
 CALL POINT_TO_MESH(NM)
 CALL PACK_MP_C(mp)
 CALL soot_c_soot_surface_oxidation(REAL(DT,C_DOUBLE), mp)
END SUBROUTINE SOOT_SURFACE_OXIDATION

! ===========================================================================
! DROPLET_SCRUBBING — 液滴洗涤
! ===========================================================================
SUBROUTINE DROPLET_SCRUBBING(IP,NM,DT,DT_P)
 INTEGER, INTENT(IN) :: IP,NM
 REAL(EB), INTENT(IN) :: DT,DT_P
 TYPE(SOOT_MP_C) :: mp
 TYPE(LAGRANGIAN_PARTICLE_TYPE), POINTER :: LP
 TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
 TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1
 CALL POINT_TO_MESH(NM)
 CALL PACK_MP_C(mp)
 LP => LAGRANGIAN_PARTICLE(IP)
 BC => BOUNDARY_COORD(LP%BC_INDEX)
 B1 => BOUNDARY_PROP1(LP%B1_INDEX)
 mp%LP_U_VAL = LP%U; mp%LP_V_VAL = LP%V; mp%LP_W_VAL = LP%W
 mp%LP_RADIUS_VAL = LP%RADIUS; mp%LP_RVC_VAL = LP%RVC; mp%LP_PWT_VAL = LP%PWT
 mp%LP_BC_INDEX_VAL = LP%BC_INDEX; mp%LP_B1_INDEX_VAL = LP%B1_INDEX
 mp%LP_IIG_VAL = BC%IIG; mp%LP_JJG_VAL = BC%JJG; mp%LP_KKG_VAL = BC%KKG
 mp%LP_BP1_AREA_VAL = B1%AREA; mp%LP_BP1_TMP_F_VAL = B1%TMP_F
 mp%LP_BP1_RHO_G_VAL = B1%RHO_G; mp%LP_BP1_TMP_G_VAL = B1%TMP_G
 CALL soot_c_droplet_scrubbing(INT(IP-1,C_INT), REAL(DT,C_DOUBLE), REAL(DT_P,C_DOUBLE), mp)
END SUBROUTINE DROPLET_SCRUBBING

! ===========================================================================
! PARTICLE_RADIUS — 模块变量访问函数（兼容原始 Fortran 接口）
! ===========================================================================
FUNCTION PARTICLE_RADIUS(N,I) RESULT(R)
 INTEGER, INTENT(IN) :: N,I
 REAL(EB) :: R
 R = soot_c_particle_radius(INT(N-1,C_INT), INT(I-1,C_INT))
END FUNCTION PARTICLE_RADIUS

! ===========================================================================
! C++ → Fortran 回调: 物理函数 extern "C" 封装
! 从 C++ 侧调用, 委托给真正的 FDS PHYSICAL_FUNCTIONS 模块
! ===========================================================================

SUBROUTINE fds_get_viscosity(zz_arr, mu_out, tmpg) BIND(C)
  USE ISO_C_BINDING, ONLY: C_DOUBLE, C_PTR
  TYPE(C_PTR), INTENT(IN), VALUE :: zz_arr
  REAL(C_DOUBLE), INTENT(OUT) :: mu_out
  REAL(C_DOUBLE), INTENT(IN), VALUE :: tmpg
  REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES), MU_LOC
  CALL COPY_FROM_C(zz_arr, ZZ_GET, N_TRACKED_SPECIES)
  CALL GET_VISCOSITY(ZZ_GET, MU_LOC, TMPG)
  mu_out = MU_LOC
END SUBROUTINE fds_get_viscosity

SUBROUTINE fds_get_conductivity(zz_arr, k_out, tmpg) BIND(C)
  USE ISO_C_BINDING, ONLY: C_DOUBLE, C_PTR
  TYPE(C_PTR), INTENT(IN), VALUE :: zz_arr
  REAL(C_DOUBLE), INTENT(OUT) :: k_out
  REAL(C_DOUBLE), INTENT(IN), VALUE :: tmpg
  REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES), K_LOC
  CALL COPY_FROM_C(zz_arr, ZZ_GET, N_TRACKED_SPECIES)
  CALL GET_CONDUCTIVITY(ZZ_GET, K_LOC, TMPG)
  k_out = K_LOC
END SUBROUTINE fds_get_conductivity

SUBROUTINE fds_get_mass_fraction(zz_arr, idx, y_out) BIND(C)
  USE ISO_C_BINDING, ONLY: C_DOUBLE, C_INT, C_PTR
  TYPE(C_PTR), INTENT(IN), VALUE :: zz_arr
  INTEGER(C_INT), INTENT(IN), VALUE :: idx
  REAL(C_DOUBLE), INTENT(OUT) :: y_out
  REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES), Y_LOC
  CALL COPY_FROM_C(zz_arr, ZZ_GET, N_TRACKED_SPECIES)
  CALL GET_MASS_FRACTION(ZZ_GET, INT(idx), Y_LOC)
  y_out = Y_LOC
END SUBROUTINE fds_get_mass_fraction

SUBROUTINE fds_get_molecular_weight(zz_arr, mw_out) BIND(C)
  USE ISO_C_BINDING, ONLY: C_DOUBLE, C_PTR
  TYPE(C_PTR), INTENT(IN), VALUE :: zz_arr
  REAL(C_DOUBLE), INTENT(OUT) :: mw_out
  REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES), MW_LOC
  CALL COPY_FROM_C(zz_arr, ZZ_GET, N_TRACKED_SPECIES)
  CALL GET_MOLECULAR_WEIGHT(ZZ_GET, MW_LOC)
  mw_out = MW_LOC
END SUBROUTINE fds_get_molecular_weight

SUBROUTINE fds_get_specific_heat(zz_arr, cp_out, tmpg) BIND(C)
  USE ISO_C_BINDING, ONLY: C_DOUBLE, C_PTR
  TYPE(C_PTR), INTENT(IN), VALUE :: zz_arr
  REAL(C_DOUBLE), INTENT(OUT) :: cp_out
  REAL(C_DOUBLE), INTENT(IN), VALUE :: tmpg
  REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES), CP_LOC
  CALL COPY_FROM_C(zz_arr, ZZ_GET, N_TRACKED_SPECIES)
  CALL GET_SPECIFIC_HEAT(ZZ_GET, CP_LOC, TMPG)
  cp_out = CP_LOC
END SUBROUTINE fds_get_specific_heat

SUBROUTINE fds_get_specific_gas_constant(zz_arr, rsum_out) BIND(C)
  USE ISO_C_BINDING, ONLY: C_DOUBLE, C_PTR
  TYPE(C_PTR), INTENT(IN), VALUE :: zz_arr
  REAL(C_DOUBLE), INTENT(OUT) :: rsum_out
  REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES), RSUM_LOC
  CALL COPY_FROM_C(zz_arr, ZZ_GET, N_TRACKED_SPECIES)
  CALL GET_SPECIFIC_GAS_CONSTANT(ZZ_GET, RSUM_LOC)
  rsum_out = RSUM_LOC
END SUBROUTINE fds_get_specific_gas_constant

SUBROUTINE fds_get_average_specific_heat(zz_arr, cpbar_out, tmpg) BIND(C)
  USE ISO_C_BINDING, ONLY: C_DOUBLE, C_PTR
  TYPE(C_PTR), INTENT(IN), VALUE :: zz_arr
  REAL(C_DOUBLE), INTENT(OUT) :: cpbar_out
  REAL(C_DOUBLE), INTENT(IN), VALUE :: tmpg
  REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES), CPBAR_LOC
  CALL COPY_FROM_C(zz_arr, ZZ_GET, N_TRACKED_SPECIES)
  CALL GET_AVERAGE_SPECIFIC_HEAT(ZZ_GET, CPBAR_LOC, TMPG)
  cpbar_out = CPBAR_LOC
END SUBROUTINE fds_get_average_specific_heat

SUBROUTINE fds_d_z_lookup(tmp_val, ns_val, d_out) BIND(C)
  USE ISO_C_BINDING, ONLY: C_DOUBLE, C_INT
  REAL(C_DOUBLE), INTENT(IN), VALUE :: tmp_val
  INTEGER(C_INT), INTENT(IN), VALUE :: ns_val
  REAL(C_DOUBLE), INTENT(OUT) :: d_out
  INTEGER :: ITMP
  ITMP = MIN(I_MAX_TEMP, NINT(REAL(tmp_val, EB)))
  d_out = D_Z(ITMP, INT(ns_val))
END SUBROUTINE fds_d_z_lookup


SUBROUTINE COPY_FROM_C(cptr, f_arr, n)
  USE ISO_C_BINDING, ONLY: C_PTR, C_F_POINTER
  TYPE(C_PTR), INTENT(IN) :: cptr
  REAL(EB), INTENT(OUT) :: f_arr(:)
  INTEGER, INTENT(IN) :: n
  REAL(EB), POINTER, DIMENSION(:) :: fptr
  CALL C_F_POINTER(cptr, fptr, [n])
  f_arr(1:n) = fptr(1:n)
END SUBROUTINE COPY_FROM_C

END MODULE SOOT_ROUTINES
